# Generated by Django 4.2 on 2023-04-26 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_name_item_title_item_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='author',
            field=models.CharField(default='jon', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='photo',
            field=models.ImageField(default='jon', upload_to='images/'),
            preserve_default=False,
        ),
    ]
