# Generated by Django 4.2 on 2023-04-27 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Appliances', 'Appliances'), ('Clothes', 'Clothes'), ('Education', 'Education'), ('Electronics', 'Electronics'), ('Free', 'Free'), ('Home & Garden', 'Home & Garden'), ('Miscellaneous', 'Miscellaneous'), ('Music', 'Music'), ('Sports', 'Sports'), ('Vehicles', 'Vehicles')], default='Miscellaneous', max_length=20),
        ),
    ]
