# Generated by Django 4.2 on 2023-05-03 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='contact',
            field=models.CharField(default='1800sellnow', max_length=50),
            preserve_default=False,
        ),
    ]
